name: Build and Deploy Jekyll to Github Pages

on:
  push:
    branches: [ master ]
    
jobs:
  jekyll:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.0

      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v3.3.1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'npm'
      
      - name: Build Jekyll 🏗
        uses:  helaili/jekyll-action@v2
        with:
          #token: ${{ secrets.GH_PAGES_TOKEN }}
          #target_branch: 'gh-pages'
          jekyll_src: './'
          jekyll_build_options: '--destination ./_site'
          build_only: true

      - name: Install node dependencies
        run: npm install

      - name: Optimize AMP ⚡ and Minify HTML 🗜
        run: |
          sudo chmod -R 777 ./_site
          npx gulp build

      - name: Deploy to gh-page 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: '_site'
